import './globals.css'
import { Inter } from 'next/font/google'

import { ThemeContextProvider } from '@/utils/ThemeContextProvider';
import Navbar from '@/components/capa/Navbar';
import Footer from '@/components/capa/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Instar - Sistemas Web',
  description: 'Generated by Instar',
}

export default function RootLayout({ children }) {

  return (
    <html lang="pt-br">
      <body className={`${inter.className}`}>
        <ThemeContextProvider>
          {children}
        </ThemeContextProvider>
      </body>
    </html>
  )
}
